# Setup

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
from IPython.display import clear_output

!pip3 install pyprind

clear_output()

# Instructions

* Clone the notebook to your drive.
* The notebook has to be submitted in the form of a link giving us **view access**. Share this link in your application.

* If you still have any queries, you can reach out to the [core team](https://www.notion.so/Club-Contacts-70a4823e0ae34f35a0aa5d479e449915)



# Common Technical Questionnaire


### Question 1

Supervised learning is a type of machine learning where the inputs and outputs are mapped through
a family of equations, the machine learning model essentially picks the right curve to fit the data.
Quantile Regression is a type of supervised learning technique used in statistics and economics. One
advantage of quantile regression relative to ordinary least squares regression is that the quantile
regression estimates are more robust against outliers in the response measurements.

QuantileLossτ (y, ˆy) =
{

                           τ · (y − ˆy) if y > ˆy

                          (1 − τ ) · (ˆy − y) if y ≤ ˆy
}

where τ is Quantile whose value lies between 0 and 1.
Please use this template provided and make changes accordingly for this question alone.
Implement a simple Neural Network consisting of 4 nodes, one hidden layer consisting of 5 nodes
and output layer consisting of two nodes. Perform quantile regression on the model and observe
the loss.
**Bonus: Play around with the value of τ to find what value achieves convergence quicker.**



An example implementation of a simple manual neural network is provided. You may use this as inspiration to complete the task at hand.

In [ ]:
# Imports

import torch

In [ ]:
# Initializing the Parameters and the Variables
# y = a*x + b
torch.set_grad_enabled(True)

def loss_function(output, target):
  # f=torch.zeros(2,2)
  # for i in range(0,2):
  #   for j in range(0,2):
  #     h=output[i][j]-target[i][j]
  #     if h.item()>0:
  #       f[i][j]=t*(h)
  #     else:
  #       f[i][j]=(t-1)*(h)
  # loss=torch.mean(f)
  error = output-target
  loss= torch.mean(torch.max(t*error,(t-1)*error)) #Fill the loss function here
  return loss


x = torch.rand((2, 4), requires_grad=False)
y = torch.rand((2, 2), requires_grad=False)


for i in range(1,10,1):  #itrating for different values of t

  t=i/10
  print('t=',i/10)
  a0 = torch.rand((4, 5), requires_grad=True)
  b0 = torch.rand((2, 5), requires_grad=True)

  a1 = torch.rand((5,2), requires_grad=True)     #For the output layer.    Fill in the dimensions appropriately
  b1 = torch.rand((2,2), requires_grad=True)
  print(y)
  for l in range (5000):#forward passing
    y1 = x@a0 + b0
    y_pred= y1@a1 + b1                              #Fill in the matrix multiplication equation
 # Computing Loss
    loss = loss_function(y_pred, y)
 # Back Propogation
    loss.backward()

# Updating Gradients
    with torch.no_grad():
      a0 = a0 - 0.001*a0.grad
      a0.requires_grad=True
      b0 = b0 - 0.001*b0.grad
      b0.requires_grad=True
      a1 = a1 - 0.001*a1.grad
      a1.requires_grad=True
      b1 = b1 - 0.001*b1.grad
      b1.requires_grad=True

  print(loss.item())
  print("for t =",i/10,"  ",y_pred)



t= 0.1
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.018151847645640373
for t = 0.1    tensor([[0.7289, 0.3252],
        [0.9475, 0.6855]], grad_fn=<AddBackward0>)
t= 0.2
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.027162091806530952
for t = 0.2    tensor([[0.5568, 0.3217],
        [0.9485, 0.6811]], grad_fn=<AddBackward0>)
t= 0.3
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.05937808007001877
for t = 0.3    tensor([[0.8051, 0.3206],
        [0.9476, 0.6810]], grad_fn=<AddBackward0>)
t= 0.4
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.0011655668495222926
for t = 0.4    tensor([[0.0209, 0.3197],
        [0.9516, 0.6808]], grad_fn=<AddBackward0>)
t= 0.5
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.01592642441391945
for t = 0.5    tensor([[0.1400, 0.3210],
        [0.9482, 0.6831]], grad_fn=<AddBackward0>)
t= 0.6
tensor([[0.0150, 0.3208],
        [0.9479, 0.6811]])
0.00042732732254080474
for t = 0.6    tensor([[0.0146, 0.3188],
        [0.9

---

In [ ]:
#so ofr quantile=0.6 we got our best result